### ISSUE TITLE
Only first release get uploaded when multiple BOSH releases are referenced in deployment manifest

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry-incubator/bosh-workspace#36]
I’m using a BOSH workspace and inside the deployment manifest it references two BOSH releases . When I call `bosh prepare deployment` everything works OK with the first release but the second one doesn't get uploaded.
What I see in the logs is:
```
Uploading 'release/2'

Copying packages
----------------
release (ffa8618912f373724b8f4394aaedbe57dd07065c) MISSING
```
I'm quite new to Ruby, BOSH and CF but I think I figure out why this happens. The issue seems to be in [release_helper.rb](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/3b09905d573ab9ea76bbfd7f818c06dbc6d1a884/lib/bosh/workspace/helpers/release_helper.rb#L28). 

```
def release_cmd
   @release_cmd ||= Bosh::Cli::Command::Release::UploadRelease.new
end
```
`ReleaseHelper` has an instance variable `release_cmd`. This variable is instantiated only once and used for the upload. The variable has state and it still points to the first release when the second one is performed. A fix could be to instantiate `UploadRelease` for each release. Is there a reason to avoid multiple instances of `UploadRelease`?

**Comment by drnic** [comment]
What is the 2nd bosh release you're referring to? Can you paste in your deployment file?

**Comment by rkoster** [comment]
It should iterate over all releases as can be seen [here](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/cli/commands/prepare.rb#L45-L59)

**Comment by beyhan** [comment]
In my example it iterates over all releases but only the first release in the list is processed and for the second one you get the error message `release (ffa8618912f373724b8f4394aaedbe57dd07065c) MISSING`. Running `bosh prepare deployment` a second time uploads also the second release and everything is OK. 

Sorry, I can't paste it here but it looks likes this

```
---
name: my-release
director_uuid: <some-uuid>

releases:
  - name: release
    version: 18
    git: <some-git-url>
  - name: release2
    version: 2
    git: <some-git-url>
stemcells:
  - name: BOSH-Stemcell
    version: <some-version>

templates:
  - release/properties.yml
  - release2/properties.yml

meta: {}
```

**Comment by rkoster** [comment]
Does it start downloading blobs the first time for the second release. Because the MISSING message looks like something blob related. If so this would mean the bosh-workspace has delegated the release upload properly but it failing halfway (maybe due to networking?)

**Comment by drnic** [comment]
If they are your internal bosh releases - can you confirm you have uploaded blobs, cut final releases, etc?




If you clone the repo somewhere and run "bosh sync blobs" what happens?

**Comment by beyhan** [comment]
I create an example with an open bosh workspace to reproduce the issue

Prerequisite is a BOSH lite setup

```
git clone https://github.com/cloudfoundry-community/logsearch-boshworkspace.git
cd logsearch-boshworkspace
```
Extend the worksapce with the [docker-boshrelease](https://github.com/cf-platform-eng/docker-boshrelease.git).  

* My `deployments/logsearch-warden.yml` looks like 

```
---
name: logsearch-warden
director_uuid: current
releases:
- name: logsearch
  version: 18
  git: https://github.com/logsearch/logsearch-boshrelease.git
- name: docker
  version: 6
  git: https://github.com/cf-platform-eng/docker-boshrelease.git

stemcells:
- name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: 389

templates:
- logsearch/deployment.yml
- logsearch/jobs.yml
- logsearch/properties.yml
- logsearch/infrastructure-warden.yml
- logsearch/logstash-filters.yml
- docker-deployment.yml
- docker-properties.yml
- docker-jobs.yml
- docker-warden.yml

meta:
  cfcontainersbroker:
    cc_api_uri: "https://api.10.244.0.34.xip.io"
    external_host: "cf-containers-broker.10.244.0.34.xip.io"
  nats:
    user: nats
    password: nats
    port: 4222
    machines:
      - 10.244.0.6
```

* Make sure the required docker manifests are available. I just copied them into the `templates` folder of logsearch-boshworksapce. Required are:
```
- docker-deployment.yml
- docker-properties.yml
- docker-jobs.yml
- docker-warden.yml
```
* Make sure BOSH lite doesn't have any logsearch and docker releases

```
bosh releases
bosh delete release logsearch
bosh delete release docker
```

After that try to prepare deployment 
```
bosh deployment logsearch-warden
bosh prepare deployment
```
The result on my machine is. The logsearch release is uploaded as expected. For the second release in this case docker I get following:
```
Uploading 'docker/6'

Copying packages
----------------
ruby (1)                      SKIP
docker (3)
MISSING
Cannot find package with checksum `f2139f61cc2ea135942e715dff2e95b61fffcf0

```
Executing `bosh prepare deployment` for a second time works and docker release is uploaded also without any errors. I hope this can help to narrow the issue.
