### ISSUE TITLE
[idea] Colocation helper

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/bosh-workspace#45]
Add a post spiff merge task which automatically colocates jobs based on the schema defined in the deployment file:

```yaml
colocation:
  - name: data_z1
    jobs: [postgresql_z1, etcd_z1]
  - name: api_z1
    jobs: [api_z1, gorouter_z1, haproxy_z1]
```

Should also take care of updating static_ips used in properties.
