### ISSUE TITLE
Support release upload from URL / local file

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bosh-workspace#58]
Would it be possible to add the capability of uploading a given release by URL (and maybe also by local file) during `prepare deployment`?

Maybe something similar to the new bosh-init manifest format:

```yaml
releases:
- name: bosh
  url: http://company_internal_host/github.com/cloudfoundry/bosh?v=155
  sha1: 875ac9a0df0bdcd449d612f07459b17c28304156
  path: release
- name: logsearch-shipper
  url: file://./releases/logsearch-shipper.tgz
  sha1: b6889630717ac4d9b25b407f887a01efe064b52c
```

The reasoning behind this is as you might have already guessed by looking at the first example `http://company_internal_host/...`, to be able to use bosh-workspace in an environment where you don't have internet access to download releases.
They are provided either via http through an internal-access-only host, or maybe even as a tgz file already available on the filesystem.

In such cases bosh-workspace should basically do a `bosh upload release <URL|file>` for these.
